import type { Metadata } from "next";
import { BigShouldersDisplay } from '@/fonts';

import "../styles/globals.scss";

import AOSProvider from '@/components/AOSProvider';
import Navigation from "@/components/Navigation";
import GlobalInfo from "@/components/GlobalInfo";
import BasicUserInfo from "@/components/BasicUserInfo";
import ActiveQuest from "@/components/ActiveQuest";

export const metadata: Metadata = {
  title: "New React.js + Next webpage",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={BigShouldersDisplay.className}>
        <AOSProvider>
          <div className="wrapper">
            <div className="header">
              <GlobalInfo />
            </div>
            <div className="sidebar">
              <BasicUserInfo />
            </div>
            <main className="main">
              {children}
            </main>
            <ActiveQuest />
            
            <Navigation />
          </div>
        </AOSProvider>
      </body>
    </html>
  );
}



{/* <div className="wrapper">
        <div className="header">header</div>
        <div className="sidebar">sidebar</div>
        <main className="main">
          <div className="content-container">
            <div className="small-corners"><div></div><div></div><div></div><div></div></div>

            content
          </div>
        </main>
        <div className="active-quest">Active quest</div>
        <nav className="navbar">navbar</nav>
      </div>
    
    */}